[platformio]
default_envs = esp32dev

[env]
framework = arduino
monitor_speed = 115200
upload_speed = 921600

[env:esp32dev]
platform = espressif32
board = esp32dev
board_build.partitions = min_spiffs.csv
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.0   ; pokud chceš parsovat JSON z API

[env:esp32-s3]
platform = espressif32
board = esp32-s3-devkitc-1
board_build.partitions = min_spiffs.csv