[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; OTA partition scheme - 2MB app / 2MB OTA
board_build.partitions = min_spiffs.csv

; Zvýš upload speed pro lokální flash
upload_speed = 921600

; Monitor
monitor_speed = 115200

; Knihovny
lib_deps =
    arduino-libraries/ArduinoHttpClient 